name: Mirror repository to codeberg

on: [push, delete]

jobs:
  sync-codeberg-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ssh://git@codeberg.org/ARGA/arga-frontend.git
          ssh_private_key: ${{ secrets.GIT_MIRROR_SSH_PRIVATE_KEY }}
